### ISSUE TITLE
Cannot serialize Kotlin type de.fayard.internal.RefreshVersionsExtensionImpl

### ISSUE THREAD

**Issue by luca992** [jmfayard/refreshVersions#158]
**Describe the bug**
RefreshVersions fails when adding sqldelight 1.2.2 as a dependency to the project. 1.2.1 works fine

**To Reproduce**

Build scan URL: https://gradle.com/s/fzarlapqhuaki

1. clone https://github.com/luca992/refreshVersions/tree/sqldelight-1.2.2-bug
2. In sample-android run `./gradlew --scan refreshVersions`
3. See error 
```
[luca@luca-desktop sample-android]$ ./gradlew --scan refreshVersions --stacktrace

> Task :dependencyUpdates
Failed to resolve :app:debugAndroidTestCompileClasspath
Failed to resolve :app:debugCompileClasspath
Failed to resolve :app:debugUnitTestCompileClasspath
Failed to resolve :app:releaseCompileClasspath
Failed to resolve :app:releaseUnitTestCompileClasspath

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - androidx.appcompat:appcompat:1.1.0
 - androidx.arch.core:core-testing:2.1.0
 - androidx.lifecycle:lifecycle-compiler:2.0.0
 - androidx.lifecycle:lifecycle-extensions:2.0.0
 - androidx.lifecycle:lifecycle-runtime:2.0.0
 - com.android.tools.lint:lint-gradle:26.5.0
 - com.google.android.material:material:1.0.0
 - com.nhaarman.mockitokotlin2:mockito-kotlin:2.2.0
 - com.squareup.sqldelight:gradle-plugin:1.2.2
 - com.squareup.sqldelight:runtime-jvm:1.2.2
 - com.squareup.sqldelight:sqlite-driver:1.2.2
 - org.jetbrains.kotlin:kotlin-android-extensions:1.3.50
 - org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.50
 - org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.50
 - org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.50
 - org.mockito:mockito-android:3.1.0
 - org.mockito:mockito-core:3.1.0

The following dependencies have later milestone versions:
 - com.gradle.build-scan:com.gradle.build-scan.gradle.plugin [2.4.2 -> 3.1.1]
 - com.louiscad.splitties:com.louiscad.splitties.gradle.plugin [0.1.2 -> 0.2.0]
 - de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin [0.8.0 -> 0.8.6]

Failed to determine the latest version for the following dependencies (use --info for details):
 - androidx.constraintlayout:constraintlayout
 - androidx.test:core
 - androidx.test:rules
 - androidx.test:runner
 - androidx.test.espresso:espresso-core
 - junit:junit

Gradle release-candidate updates:
 - Gradle: [5.6.2 -> 6.1.1 -> 6.2-rc-1]

Generated report file build/dependencyUpdates/report.json

> Task :refreshVersions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':refreshVersions'.
> Cannot serialize Kotlin type de.fayard.internal.RefreshVersionsExtensionImpl. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapter from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':refreshVersions'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.StartSnapshotTaskInputsBuildOperationTaskExecuter.execute(StartSnapshotTaskInputsBuildOperationTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.IllegalArgumentException: Cannot serialize Kotlin type de.fayard.internal.RefreshVersionsExtensionImpl. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapter from the moshi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.
	at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:83)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:72)
	at de.fayard.internal.PluginConfig$moshiAdapter$1.invoke(PluginConfig.kt:141)
	at de.fayard.internal.PluginConfig$moshiAdapter$1.invoke(PluginConfig.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.fayard.internal.PluginConfig.getExtensionAdapter$plugin(PluginConfig.kt)
	at de.fayard.internal.RefreshVersionsExtensionImpl.toString(RefreshVersionsExtensionImpl.kt:25)
	at de.fayard.RefreshVersionsTask$dependencyGraph$2.invoke(RefreshVersionsTask.kt:54)
	at de.fayard.RefreshVersionsTask$dependencyGraph$2.invoke(RefreshVersionsTask.kt:20)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at de.fayard.RefreshVersionsTask.getDependencyGraph(RefreshVersionsTask.kt)
	at de.fayard.RefreshVersionsTask.taskActionGradleProperties(RefreshVersionsTask.kt:37)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
	... 35 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
2 actionable tasks: 2 executed

Publishing build scan...
https://gradle.com/s/arvepnjnp5vz2

```

**Comment by Jasperhino** [comment]
Having a similar issue

```
D:\Studium\BP\sensor-hub-app>gradlew refreshVersions
Starting a Gradle Daemon, 2 incompatible and 5 stopped Daemons could not be reused, use --status for details

> Task :dependencyUpdates
Failed to resolve :app:debugAndroidTestCompileClasspath
Failed to resolve :app:debugCompileClasspath
Failed to resolve :app:debugUnitTestCompileClasspath
Failed to resolve :app:releaseCompileClasspath
Failed to resolve :app:releaseUnitTestCompileClasspath

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - android.arch.core:core-testing:none
 - androidx.appcompat:appcompat:1.1.0
 - androidx.constraintlayout:constraintlayout:1.1.3
 - androidx.core:core-ktx:1.1.0
 - androidx.lifecycle:lifecycle-livedata-ktx:2.2.0
 - androidx.lifecycle:lifecycle-process:2.2.0
 - androidx.lifecycle:lifecycle-runtime-ktx:2.2.0
 - androidx.lifecycle:lifecycle-service:2.2.0
 - androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0
 - androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
 - androidx.navigation:navigation-fragment-ktx:2.1.0
 - androidx.navigation:navigation-ui-ktx:2.1.0
 - androidx.preference:preference:1.1.0
 - androidx.test:rules:1.2.0
 - androidx.test:runner:1.2.0
 - androidx.test.espresso:espresso-contrib:3.2.0
 - androidx.test.espresso:espresso-core:3.2.0
 - androidx.test.ext:junit:1.1.1
 - androidx.work:work-runtime-ktx:2.3.4
 - ch.hevs.biovotion.vsm.ble:vsm:5.2.0
 - com.android.tools.build:aapt2:3.5.3-5435860
 - com.android.tools.lint:lint-gradle:26.5.3
 - com.auth0.android:jwtdecode:2.0.0
 - com.biovotion.android.decoder:decoder:2.9.5
 - com.fasterxml.jackson.module:jackson-module-kotlin:2.10.2
 - com.github.weliem:blessed-android:1.8
 - com.google.android.gms:play-services-location:17.0.0
 - com.google.android.material:material:1.0.0
 - com.google.code.findbugs:jsr305:3.0.2
 - com.google.truth:truth:1.0.1
 - com.jjoe64:graphview:4.2.2
 - com.squareup.retrofit2:converter-jackson:2.6.2
 - com.squareup.retrofit2:retrofit:2.6.2
 - com.vanniktech.android.junit.jacoco:com.vanniktech.android.junit.jacoco.gradle.plugin:0.16.0
 - de.jansauer.printcoverage:de.jansauer.printcoverage.gradle.plugin:2.0.0
 - de.mannodermaus.junit5:android-test-core:1.2.0
 - de.mannodermaus.junit5:android-test-runner:1.2.0
 - io.mockk:mockk:1.9.1
 - io.mockk:mockk-android:1.10.0
 - io.objectbox:objectbox-android:2.5.1
 - io.objectbox:objectbox-gradle-plugin:2.5.1
 - io.objectbox:objectbox-kotlin:2.5.1
 - io.objectbox:objectbox-processor:2.5.1
 - io.objectbox:objectbox-windows:2.5.1
 - io.sentry:sentry-android:1.7.29
 - org.jacoco:org.jacoco.agent:0.7.9
 - org.jetbrains.kotlin:kotlin-android-extensions:1.3.61
 - org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.61
 - org.jetbrains.kotlin:kotlin-annotation-processing-gradle:1.3.61
 - org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.72
 - org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61
 - org.jetbrains.kotlinx:kotlinx-coroutines-core:none
 - org.junit.jupiter:junit-jupiter-api:5.6.0
 - org.junit.jupiter:junit-jupiter-engine:5.6.0
 - org.junit.jupiter:junit-jupiter-params:5.6.0
 - org.slf4j:slf4j-nop:1.7.30

The following dependencies exceed the version found at the milestone revision level:
 - androidx.navigation:navigation-safe-args-gradle-plugin [2.3.0-alpha06 <- 2.2.2]
     https://developer.android.com/topic/libraries/architecture/index.html

The following dependencies have later milestone versions:
 - com.android.tools.build:gradle [3.6.2 -> 4.0.0]
     https://developer.android.com/studio
 - com.github.triplet.play:com.github.triplet.play.gradle.plugin [2.6.2 -> 2.7.5]
 - com.squareup.okhttp3:mockwebserver [4.5.0 -> 4.7.2]
     https://square.github.io/okhttp/
 - de.fayard.refreshVersions:de.fayard.refreshVersions.gradle.plugin [0.8.6 -> 0.9.4]
 - de.mannodermaus.gradle.plugins:android-junit5 [1.6.0.0 -> 1.6.2.0]
     https://github.com/mannodermaus/android-junit5
 - no.nordicsemi.android:ble [2.1.1 -> 2.2.0]
     https://github.com/NordicSemiconductor/Android-BLE-Library
 - no.nordicsemi.android.support.v18:scanner [1.4.0 -> 1.4.3]
     https://github.com/NordicSemiconductor/Android-Scanner-Compat-Library
 - org.jacoco:org.jacoco.ant [0.7.9 -> 0.8.5]
     http://jacoco.org
 - org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin [9.1.1 -> 9.2.1]

Gradle release-candidate updates:
 - Gradle: [6.3 -> 6.5]

Generated report file D:\Studium\BP\sensor-hub-app\build\dependencyUpdates\report.json

> Task :refreshVersions FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':refreshVersions'.
> Cannot serialize Kotlin type de.fayard.internal.RefreshVersionsExtensionImpl. Reflective serialization of Kotlin classes without using kotlin-reflect has undefined and unexpected behavior. Please use KotlinJsonAdapter from the mos
hi-kotlin artifact or use code gen from the moshi-kotlin-codegen artifact.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 18s
2 actionable tasks: 2 executed

```

**Comment by luca992** [comment]
working for me  now with latest version
