### ISSUE TITLE
java.lang.NumberFormatException: For input string: "20090811081019"

### ISSUE THREAD

**Issue by NikkyAI** [jmfayard/refreshVersions#188]
**Checklist**

- [ ] I verified that the task `./gradlew :dependencyUpdates` works correctly. If that's not the case, it's better to submit a bug-report to https://github.com/ben-manes/gradle-versions-plugin 
there is no task `dependencyUpdates` ?
- [x] I tried to reproduce the bug within `sample-groovy`, `sample-kotlin` or `sample-versionsOnlyMode` 
- [x] I have run with `$ ./gradlew --scan buildSrcVersions` or `$./gradlew --scan refreshVersions` to [provide a Build Scan URL](https://dev.to/jmfayard/the-one-gradle-trick-that-supersedes-all-the-others-5bpg)
 
**Describe the bug**

scan: https://scans.gradle.com/s/bvm2k6uha4tpi

when i add this dependency

```
implementation(group = "org.scala-lang", name = "scala-library", version = "_")
// same thing: implementation("org.scala-lang:scala-library:_")
```

the gradle refresh (or refreshVersions task) crashes with this log

```
FAILURE: Build failed with an exception.

* What went wrong:
For input string: "20090811081019"

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
com.intellij.openapi.externalSystem.model.ExternalSystemException: For input string: "20090811081019"
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.addBuildModels(ProjectImportAction.java:272)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:130)
	at org.jetbrains.plugins.gradle.model.ProjectImportAction.execute(ProjectImportAction.java:56)
	at org.gradle.tooling.internal.consumer.connection.InternalBuildActionAdapter.execute(InternalBuildActionAdapter.java:79)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner$ActionRunningListener.runAction(ClientProvidedPhasedActionRunner.java:120)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner$ActionRunningListener.run(ClientProvidedPhasedActionRunner.java:110)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner$ActionRunningListener.buildFinished(ClientProvidedPhasedActionRunner.java:104)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:382)
	at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:364)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:352)
	at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:339)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy14.buildFinished(Unknown Source)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:167)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:113)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:86)
	at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
	at org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)
	at org.gradle.tooling.internal.provider.runner.ClientProvidedPhasedActionRunner.run(ClientProvidedPhasedActionRunner.java:60)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:78)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:52)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:68)
	at org.gradle.tooling.internal.provider.SessionScopeBuildActionExecuter.execute(SessionScopeBuildActionExecuter.java:38)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:60)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:48)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:32)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:68)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:27)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
java.lang.NumberFormatException: For input string: "20090811081019"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.parseInt(Integer.java:615)
	at de.fayard.versions.extensions.VersionExtensionsKt.toComparableList-F2_lFBY(VersionExtensions.kt:116)
	at de.fayard.versions.extensions.VersionExtensionsKt.access$toComparableList-F2_lFBY(VersionExtensions.kt:1)
	at de.fayard.versions.extensions.VersionExtensionsKt$createVersionComparator$1.compare-3RWntRo(VersionExtensions.kt:57)
	at de.fayard.versions.extensions.VersionExtensionsKt$createVersionComparator$1.compare(VersionExtensions.kt:45)
	at java.util.Collections$ReverseComparator2.compare(Collections.java:5232)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:356)
	at java.util.TimSort.sort(TimSort.java:234)
	at java.util.Arrays.sort(Arrays.java:1438)
	at kotlin.collections.ArraysKt___ArraysJvmKt.sortWith(_ArraysJvm.kt:1864)
	at kotlin.collections.CollectionsKt___CollectionsKt.sortedWith(_Collections.kt:949)
	at de.fayard.versions.internal.LatestVersionsRetrievalKt$getDependencyVersionsCandidates$2.invokeSuspend(LatestVersionsRetrieval.kt:35)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.UndispatchedCoroutine.afterResume(Builders.common.kt:207)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)



* Get more help at https://help.gradle.org

BUILD FAILED in 8s
```

**To Reproduce**

Build scan URL: https://scans.gradle.com/s/xxxxxxxxxx

buildscript to repoduce `build.gradle.kts`:
```kotlin
plugins {
    id("scala")
    id("de.fayard.dependencies")
}

repositories {
    jcenter()
    mavenCentral()
}

dependencies {
    implementation(group = "org.scala-lang", name = "scala-library", version = "_")
}
```

**Expected behavior**

no crash ?

I thik the scala plugin adds some repositories (ivy?) and refreshVersions seems to not support those

**Comment by LouisCAD** [comment]
The versions sorter will eventually get removed as part of #153, which will fix this issue.

When it comes to ivy repositories, refreshVersions doesn't support them for now.
If you need it, please open a separate issue, and I'll be grateful if you also link some info as to where to get the versions lists ordered as maven-metadata.xml files do.

**Comment by NikkyAI** [comment]
looking at this more i don't think ivy is actually involved...
the scala artifact is on mavencentral here: https://repo.maven.apache.org/maven2/org/scala-lang/scala-library/maven-metadata.xml

it seems like the parsing freaks out on this tag: `<version>2.8.0.r18462-b20090811081019</version>`
which is reasonable because the number is too big
this line is responsible: https://github.com/jmfayard/refreshVersions/blob/develop/plugins/core/src/main/kotlin/de/fayard/versions/extensions/VersionExtensions.kt#L116

how should this be handled ?
it could be replaced with `toLong()` to handle larger numbers
purely alphanumerical comparison between the different components should work as well right ?
as long as they are split on `.`, `-`, `+`, etc

so #176 already found this (i suck at searching for duplicate issues)
and #153 will fix it
the workaround of hardcoding a single thing is not too bad

**Comment by DanySK** [comment]
It should be using BigInteger I believe rather than long, or we're just moving the problem some steps away.

**Comment by LouisCAD** [comment]
@NikkyAI Please, use permalinks next time (press the "y" key before copying from the address bar), because as I moved code, it's now pointing to 404.

Regardless, I think I see what can cause the failure, and this version parsing should go away as part of #153.
I'll try to finally work on it this weekend.

**Comment by LouisCAD** [comment]
Do you know what the "20090811081019" number is supposed to represent?

**Comment by DanySK** [comment]
@LouisCAD my educated guess would be that it represents the build date: august 11th, 2009, at 08:10:19.
A similarly mistaken version is available for commons-io.

**Comment by LouisCAD** [comment]
I see. It fits in a `Long`, just like a timestamp would. I think if this code keeps on being used, I'll just support `Long` in place of `Int`, and not use `BigInteger` for the sake of performance. Plus reading the longest long is already insane, I don't see how it would land in the version name of a legit library.

**Comment by DanySK** [comment]
@LouisCAD not using BigInteger "for the sake of performance" in a Gradle plugin, without any profiling in place indicating a possible problem (there will be none) is a gargantuan mistake that will eventually backfire as soon as someone includes a longer date format.
It's not an intensive computation, I warmly recommend to favor logic and design over performance, as there is not even and indication that it might be an actual issue. Premature optimization is the root of all evil.

**Comment by LouisCAD** [comment]
> Premature optimization is the root of all evil.

@DanySK I don't like this speech, because it's often an excuse to not care about efficiency at all, and that is the root of other evils, that can end up being worse.

Anyway, I don't know yet if this code will still be used, but I know that in the current form, this can be a hot path, hence my will to make it light. Now it's very possible that the difference would be insignificant. I still think it's very unlikely that one would invent a date format made of digits only that would span over 19 digits or more (Long.MAX_VALUE is 19 digits in decimal), and put it in a version number.

I'll take my decision after work on #153 is started.

**Comment by DanySK** [comment]
@LouisCAD my point is: what do you gain in using `Long` rather than `BigInteger`? An insignificant performance/memory gain (the second more important than the former despite overall irrelevance, probably). Plus, I guess there's networking involved in version lookup, which I guess easily cannibalize the execution time.
On the other hand, what do you lose? The ability to support arbitrary-length versions.

I believe I got a decent experience in performance-critical JVM software (and related profiling/sampling/targeted optimization). I warmly recommend to begin by capturing the abstraction you actually need (in this case, an arbitrarily long sequence of digits), and only if you see that the whole abstraction is unused in practice *and* it is an actual issue for performance, then optimizing. Abstraction-first is, in my opinion, a good engineering practice.

I agree that it's rare to see a number larger than `Long.MAX_VALUE`, but both mistakes and silly versioning schemes exist (e.g., every TeX version adds a digit, and the version number converges to π). The thing is that you can't control what others do upstream, the only thing under your control is if and how to fail.

Ultimately, you are the maintainer of the software, so it's up to you to weigh the performance gain of Long over BigInteger vs. the possibility that someone comes up (by will or mistake) with a version number longer than 19 digits.

Cheers.

**Comment by LouisCAD** [comment]
Thanks for your thoughts, and sharing that fact regarding TeX versioning scheme @DanySK.

I agree with your abstraction-first principles, although you always need to beware to not over-abstract, or wrongly-abstract (which are things as well), it makes sense in this context.

If I end up using `Long`, I'll make sure to catch that `NumberFormatException` and provide an error message that can be understanded. But I'll consider `BigInteger`, it might be a good fit after all.

**Comment by DanySK** [comment]
You are welcome, thanks for your efforts
