### ISSUE TITLE
refreshVersions task fails because of an HTTP 403 (v0.10.1)

### ISSUE THREAD

**Issue by emilbutiri** [jmfayard/refreshVersions#386]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug

Running the latest (v0.10.1), the `refreshVersions` task fails because of an HTTP 403. 

```
Caused by: retrofit2.HttpException: HTTP 403 Response.error()
	at de.fayard.refreshVersions.core.internal.MavenDependencyVersionsFetcherHttp.getXmlMetadataOrNull(MavenDependencyVersionsFetcherHttp.kt:44)
	at de.fayard.refreshVersions.core.internal.MavenDependencyVersionsFetcherHttp$getXmlMetadataOrNull$1.invokeSuspend(MavenDependencyVersionsFetcherHttp.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at de.fayard.refreshVersions.core.RefreshVersionsTask.taskActionRefreshVersions(RefreshVersionsTask.kt:58)
...
```

I think it might be because of several "kotlin.bintray" URLs, please see the build scan below:

## 📱 Tech info
 - [Build Scan URL](https://scans.gradle.com/s/yx7didbhy6avi)

**Comment by emilbutiri** [comment]
Nevermind... All I had to do was to remove all `bintray` repos from my project-level `build.gradle.kts`

Thank you @LouisCAD for pointing me in the right direction
