### ISSUE TITLE
Migrating to refreshVersions breaks the build

### ISSUE THREAD

**Issue by marmistrz** [jmfayard/refreshVersions#442]
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Migrating my project to refreshVersions breaks the build

## 💣 Steps to reproduce
1. Clone the following branch: https://github.com/marmistrz/OpenMeteo/tree/deps
2. Execute `gradle refreshVersionsMigrate`
3. Execute `gradle build`. 

Then the build fails with
```
* What went wrong:
A problem occurred configuring root project 'OpenMeteo'.
> kotlin.KotlinNullPointerException (no error message)
```

## 📱 Tech info
 - [Build Scan URL](https://scans.gradle.com/s/c4o5cftrfkxv2):

**Comment by CDRussell** [comment]
I see this happening on a brand new project with basically nothing in it. This looks like a regression on `0.21.0`. If i drop back to `0.20.0` this error doesn't happen

**Comment by LouisCAD** [comment]
@CDRussell What is the type of project you created, with which IDE and which version if created from a wizard?

**Comment by CDRussell** [comment]
Created a new Android project using IntelliJ. Think I chose not to create any Activity from the wizard in case that is significant. 

Then added the 0.21.0 plug-in and tried to run `refreshVersions` and I get that error message. Changing to 0.20.0 made that error go away.

**Comment by LouisCAD** [comment]
Here's the stacktrace that shows where the problem originates:
```stacktrace
Caused by: kotlin.KotlinNullPointerException
	at de.fayard.refreshVersions.RefreshVersionsPlugin$Companion.getBundledResourceAsStream(RefreshVersionsPlugin.kt:23)
	at de.fayard.refreshVersions.RefreshVersionsPlugin$Companion.access$getBundledResourceAsStream(RefreshVersionsPlugin.kt:20)
	at de.fayard.refreshVersions.RefreshVersionsPlugin$bootstrap$1$1.invoke(RefreshVersionsPlugin.kt:85)
	at de.fayard.refreshVersions.RefreshVersionsPlugin$bootstrap$1$1.invoke(RefreshVersionsPlugin.kt:18)
	at de.fayard.refreshVersions.core.internal.VersionsPlaceholdersReplacementKt.findAnyPreviouslyMatchingVersionEntry(VersionsPlaceholdersReplacement.kt:258)
	at de.fayard.refreshVersions.core.internal.VersionsPlaceholdersReplacementKt.Copy previously matching version entry, if any, and get its version(VersionsPlaceholdersReplacement.kt:234)
	at de.fayard.refreshVersions.core.internal.VersionsPlaceholdersReplacementKt.access$Copy previously matching version entry, if any, and get its version(VersionsPlaceholdersReplacement.kt:1)
	at de.fayard.refreshVersions.core.internal.VersionsPlaceholdersReplacementKt$replaceVersionPlaceholdersFromDependencies$1.execute(VersionsPlaceholdersReplacement.kt:152)
```

**Comment by LouisCAD** [comment]
Hello, first I want to apologize for taking this long to start looking into the issue.

I also want to let you know that in case there's an exception triggered by refreshVersions, it's always helpful to share the stacktrace, as I can glance at it, even if I don't have a laptop/desktop around, ready to dive in (I look at issues a lot from the Android app).

So, I found the culprit, and I'm fixing it now, stay tuned for the hotfix release.

**Comment by LouisCAD** [comment]
The version `0.22.0` will include the fix, and if you're in a hurry, the version `0.22.0-SNAPSHOT` [is being built](https://github.com/jmfayard/refreshVersions/actions/runs/1267029054) and should be there in less than 5 minutes.
